/* eslint-disable */
// DO NOT EDIT THIS FILE.  This is a gitignored artifact created by Gulp.
// Design tokens should be edited in _patterns/00-config/config.design-tokens.yml
export const PALETTE = {
  "brand": {
    "blue": {
      "base": "#0071BC",
      "light": "#4773aa",
      "light-1": "#8ba6ca",
      "light-2": "#dce4ef",
      "dark": "#205493",
      "dark-1": "#112E51"
    },
    "ocean-blue": {
      "base": "#02bfe7",
      "light": "#9bdaf1",
      "light-1": "#e1f3f8",
      "dark": "#00a6d2",
      "dark-1": "#046b99"
    }
  },
  "grayscale": {
    "white": "#fff",
    "gray-1": "#f7f7f7",
    "gray-2": "#f1f1f1",
    "gray-3": "#d6d7d9",
    "gray-4": "#aeb0b5",
    "gray-5": "#5b616b",
    "gray-6": "#323a45",
    "black": "#212121"
  },
  "other": {
    "yellow": {
      "base": "#fad980",
      "light": "#fff1d2"
    },
    "yellow-neon": {
      "base": "#ff0"
    },
    "green": {
      "base": "#94bfa2",
      "light": "#e7f4e4"
    },
    "red": {
      "base": "#e31c3d",
      "light": "#e59393",
      "light-1": "#f9dede",
      "dark": "#cd2026",
      "dark-1": "#981b1e"
    }
  }
};

export const BOX_SHADOW = {
  "0": "none",
  "1": "0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24)",
  "2": "0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23)",
  "3": "0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23)",
  "4": "0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22)",
  "5": "0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22)"
};

export const CONSTRAINS = {
  "sm": "800px",
  "md": "1440px",
  "lg": "2200px"
};

export const BREAKPOINTS = {
  "mobile": "320px",
  "mobile-lg": "480px",
  "tablet": "640px",
  "mobile-menu": "699px",
  "tablet-lg": "880px",
  "desktop": "1024px",
  "desktop-lg": "1200px",
  "widescreen": "1400px"
};

export const COLORS = {
  "text": {
    "primary": "#212121",
    "secondary": "#5b616b",
    "on-light": "#212121",
    "on-dark": "#fff",
    "link": "#0071BC",
    "link-hover": "#205493",
    "link-active": "#205493",
    "link-visited": "#205493"
  },
  "background": {
    "site": "#fff"
  },
  "button": {
    "primary": {
      "background": "#0071BC",
      "background-hover": "#205493",
      "background-active": "#112E51",
      "text": "#fff",
      "text-hover": "#fff",
      "text-active": "#fff"
    },
    "secondary": {
      "background": "#02bfe7",
      "background-hover": "#00a6d2",
      "background-active": "#046b99",
      "text": "#fff",
      "text-hover": "#fff",
      "text-active": "#fff"
    },
    "disabled": {
      "background": "#f1f1f1",
      "text": "#aeb0b5"
    },
    "danger": {
      "background": "#e31c3d",
      "background-hover": "#cd2026",
      "background-active": "#981b1e",
      "text": "#fff",
      "text-hover": "#fff",
      "text-active": "#fff"
    }
  },
  "form": {
    "background": "#f7f7f7",
    "background-active": "#fff",
    "background-checked": "#0071BC",
    "background-unchecked": "#fff",
    "border": "#d6d7d9",
    "border-dark": "#5b616b",
    "border-light": "#f7f7f7",
    "thumb": "#5b616b",
    "track": "#aeb0b5"
  },
  "mark": {
    "background": "#ff0",
    "text": "#212121"
  },
  "selection": {
    "background": "#0071BC",
    "text": "#fff"
  },
  "table": {
    "border": "#5b616b",
    "background": "#fff",
    "background-head": "#f1f1f1",
    "background-foot": "#f1f1f1"
  },
  "ui": {
    "generic": {
      "background": "#aeb0b5",
      "background-darker": "#212121",
      "background-dark": "#323a45",
      "background-light": "#f1f1f1",
      "background-lighter": "#f7f7f7",
      "border": "#aeb0b5",
      "border-dark": "#323a45",
      "border-light": "#f1f1f1",
      "text-lighter": "#fff",
      "text-light": "#aeb0b5",
      "text-dark": "#5b616b",
      "text-darker": "#212121",
      "accent": "#0071BC",
      "accent-dark": "#112E51",
      "accent-light": "#4773aa",
      "focus": "#4773aa"
    },
    "error": {
      "background": "#f9dede",
      "border": "#e59393"
    },
    "success": {
      "background": "#e7f4e4",
      "border": "#94bfa2"
    },
    "warning": {
      "background": "#fff1d2",
      "border": "#fad980"
    }
  }
};

export const TYPOGRAPHY = {
  "font-family": {
    "primary": {
      "name": "Primary",
      "stack": "\"Source Sans Pro\", Arial, sans-serif"
    },
    "system": {
      "name": "System",
      "stack": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Oxygen-Sans\", Ubuntu, Cantarell, \"Fira Sans\", Droid Sans, sans-serif"
    },
    "monospace": {
      "name": "Monospace",
      "stack": "Menlo, Consolas, \"Lucida Console\", \"Liberation Mono\", \"Courier New\", monospace, sans-serif"
    }
  },
  "base-font-size": "16px",
  "font-size": {
    "1": "12px",
    "2": "16px",
    "3": "20px",
    "4": "24px",
    "5": "32px",
    "6": "40px",
    "7": "48px",
    "8": "56px",
    "9": "64px",
    "10": "80px"
  },
  "font-weight": {
    "light": 300,
    "regular": 400,
    "semibold": 600,
    "bold": 700
  },
  "line-height": {
    "tight": 1.1,
    "base": 1.45,
    "loose": 1.7
  },
  "display": {
    "display": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "64px",
      "font-weight": 700,
      "line-height": 1.1
    },
    "h1": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "48px",
      "font-weight": 700,
      "line-height": 1.1
    },
    "h2": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "40px",
      "font-weight": 700,
      "line-height": 1.1
    },
    "h3": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "32px",
      "font-weight": 700,
      "line-height": 1.1
    },
    "h4": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "24px",
      "font-weight": 700,
      "line-height": 1.45
    },
    "h5": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "16px",
      "font-weight": 700,
      "line-height": 1.45
    },
    "h6": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "12px",
      "font-weight": 600,
      "letter-spacing": "-0.04em",
      "line-height": 1.7,
      "text-transform": "uppercase"
    },
    "blockquote": {
      "color": "#0071BC",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "24px",
      "font-weight": 400,
      "line-height": 1.45
    },
    "body": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "16px",
      "font-weight": 400,
      "line-height": 1.45
    },
    "body-large": {
      "color": "#212121",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "20px",
      "font-weight": 400,
      "line-height": 1.45
    },
    "cite": {
      "color": "#5b616b",
      "font-family": "\"Source Sans Pro\", Arial, sans-serif",
      "font-size": "12px",
      "font-style": "normal",
      "font-weight": 600,
      "letter-spacing": ".02em",
      "line-height": 1.1
    }
  }
};

export const TRANSITIONS = {
  "ease": {
    "ease-in-out": "cubic-bezier(0.4, 0, 0.2, 1)",
    "ease-out": "cubic-bezier(0.0, 0, 0.2, 1)",
    "ease-in": "cubic-bezier(0.4, 0, 1, 1)",
    "sharp": "cubic-bezier(0.4, 0, 0.6, 1)"
  },
  "duration": {
    "shortest": "150ms",
    "short": "200ms",
    "standard": "375ms",
    "long": "400ms",
    "intro": "270ms",
    "outro": "195ms"
  }
};

export const Z_INDEX = {
  "nav": 1000,
  "drawer": 1200,
  "modal": 1300
};

export const SPACING = {
  "0": 0,
  "1": "8px",
  "2": "16px",
  "3": "24px",
  "4": "32px",
  "5": "40px",
  "6": "48px",
  "7": "56px",
  "8": "64px",
  "9": "72px",
  "10": "80px",
  "12": "96px",
  "15": "120px",
  "0.5": "4px",
  "1.5": "12px",
  "2.5": "20px"
};

export const GUTTER_WIDTH = "40px";

