extends:
  - stylelint-config-sass-guidelines
  - stylelint-config-prettier

rules:
  property-no-vendor-prefix: null
  max-nesting-depth: 3
  no-missing-end-of-source-newline: false
  selector-class-pattern:
    # "piece" regex:
    # [a-zA-Z][a-zA-Z0-9]*
    # dash-separated pieces:
    # [a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z][a-zA-Z0-9]*)*
    #
    #   Block                                              Element (optional)                                   Modifier (also optional)
    #   ----------------------------------------------     -----------------------------------------------      -----------------------------------------------
    - '^[a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z][a-zA-Z0-9]*)*(?:__[a-zA-Z][a-zA-Z0-9]*(?:-[a-zA-Z][a-zA-Z0-9]*)*)?(?:--[a-zA-Z0-9]*(?:-[a-zA-Z][a-zA-Z0-9]*)*)?$'
