version: "3.7"
services:
  gesso:
    build: .
    volumes:
      - "$PWD:/"

  # Run all scans with `docker-compose run codacy`.
  # Target a specific tool with `docker-compose run codacy analyze -t <tool>`
  codacy: &codacy
    image: codacy/codacy-analysis-cli:latest
    environment:
      CODACY_CODE: "${PWD}"
    working_dir: "${PWD}"
    command: analyze
    volumes:
      - "$PWD:$PWD"
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  # Run PHPCS linting with `docker-compose run phpcs`.
  phpcs:
    <<: *codacy
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t phpcs
    command: ''

  # Run ESLint linting with `docker-compose run eslint`.
  eslint:
    <<: *codacy
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t eslint
    command: ''
    
  # Run StyleLint linting with `docker-compose run stylelint`.
  stylelint:
    <<: *codacy
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t stylelint
    command: ''
