# This is the Compose file for command-line services.
# Anything that doesn't need to be run as part of the main `docker-compose up'
# command should reside in here and be invoked by a helper script.
version: "3.7"
services:
  gesso:
    build: ./
    init: true
    volumes:
      - ./images:/app/images:cached
      - ./js:/app/js:cached
      - ./source:/app/source:cached
      - type: volume
        source: gesso-pattern-lab
        target: /app/pattern-lab
      - type: volume
        source: gesso-css
        target: /app/css

  # Run all scans with `docker-compose run codacy` or `f1 run codacy`.
  # Target a specific tool with `docker-compose run codacy analyze -t <tool>`
  # or `f1 run codacy analyze -t <tool>`.
  codacy: &codacy
    image: codacy/codacy-analysis-cli:latest
    environment:
      CODACY_CODE: "${PWD}"
    working_dir: "${PWD}"
    command: analyze
    volumes:
      - ${PWD}:${PWD}:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  # Run PHPCS linting with `docker-compose run phpcs` or `f1 run phpcs`.
  phpcs:
    <<: *codacy
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t phpcs
    command: ''

  # Run ESLint linting with `docker-compose run eslint` or `f1 run eslint`.
  eslint:
    <<: *codacy
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t eslint
    command: ''

  # Run StyleLint linting with `docker-compose run stylelint` or `f1 run stylelint`.
  stylelint:
    <<: *codacy
    entrypoint: /opt/codacy/bin/codacy-analysis-cli analyze -t stylelint
    command: ''

volumes:
  ? gesso-pattern-lab
  ? gesso-css
