'use strict';

const { dest, lastRun, parallel, series, src, watch } = require('gulp');
const sass = require('gulp-sass');
const sourcemaps = require('gulp-sourcemaps');
const sassGlob = require('gulp-sass-glob');
const stylelint = require('gulp-stylelint');
const postcss = require('gulp-postcss');
const config = require('./pattern-lab-config.json');
const patternLab = require('@pattern-lab/core')(config);
const yaml = require('yaml');

const fs = require('fs');
const path = require('path');
const util = require('util');

const readSource = require('./lib/readSource');
const transform = require('./lib/transform');
const renderSass = require('./lib/renderSass');

const writeFile = util.promisify(fs.writeFile);
const os = require("os");

async function buildConfig() {
  const scssDir = path.join(__dirname, '/source/_patterns/00-config');
  const ymlDir = path.join(__dirname, './source/_data');

  const parsed = await readSource(
    path.join(__dirname, './source/_patterns/00-config/config.design-tokens.yml'),
  );
  const dataComment = '# DO NOT EDIT THIS FILE.  This is a gitignored artifact created by Gulp.'
    + os.EOL + '# Design tokens should be edited in _patterns/00-config/config.design-tokens.yml';

  const transformed = transform(parsed);
  const sassComment = '// DO NOT EDIT THIS FILE.  This is a gitignored artifact created by Gulp.'
    + os.EOL + '// Design tokens should be edited in config.design-tokens.yml';

  await Promise.all([
    writeFile(
      path.join(ymlDir, 'design-tokens.artifact.yml'),
      dataComment + os.EOL + yaml.stringify(transformed.data),
    ),
    writeFile(
      path.join(scssDir, '_design-tokens.artifact.scss'),
      sassComment + os.EOL + renderSass(transformed.data)),
  ]);
}

function lintStyles() {
  return src('**/*.scss', { cwd: './source', since: lastRun(lintStyles) }).pipe(
    stylelint({
      configFile: '.stylelintrc.yml',
      failAfterError: true,
      reporters: [{ formatter: 'string', console: true }],
    }),
  );
}

function buildStyles() {
  return src('*.scss', { cwd: './source' })
    .pipe(sassGlob())
    .pipe(sourcemaps.init())
    .pipe(
      sass({
        includePaths: ['./node_modules/breakpoint-sass/stylesheets'],
        precision: 10,
      }),
    )
    .pipe(
      postcss([
        require('postcss-assets')(),
        require('autoprefixer')({
          remove: false,
        }),
      ]),
    )
    .pipe(sourcemaps.write('.'))
    .pipe(dest('css'));
}

function buildPatternLab() {
  return patternLab.build({ cleanPublic: true, watch: false });
}

function fileWatch() {
  watch(
    [
      'source/**/*.scss',
      'images/*.svg',
      '!source/_patterns/00-config/_config.artifact.design-tokens.scss',
    ],
    { usePolling: true, interval: 1500 },
    series(lintStyles, buildStyles),
  );
  watch(
    ['source/_patterns/00-config/config.design-tokens.yml'],
    { usePolling: true, interval: 1500 },
    series(
      buildConfig,
      parallel(
        series(lintStyles, buildStyles),
        buildPatternLab,
      ),
    ),
  );
  watch(
    [
      'source/**/*.{twig,json,yaml,yml}',
      '!source/_patterns/00-config/config.design-tokens.yml'
    ],
    { usePolling: true, interval: 1500 },
    buildPatternLab,
  );
}

const gessoBuildConfig = (exports.gessoBuildConfig = buildConfig);
const gessoBuildPatternLab = (exports.gessoBuildPatternLab = buildPatternLab);
const gessoBuildStyles = (exports.gessoBuildStyles = series(
  lintStyles,
  buildStyles
));

const gessoBuild = (exports.gessoBuild = series(
  gessoBuildConfig,
  parallel(
    gessoBuildStyles,
    gessoBuildPatternLab
  )
));

const gessoWatch = (exports.gessoWatch = fileWatch);

exports.default = series(gessoBuild, gessoWatch);
