<?php

/**
 * Implements hook_form_system_theme_settings_alter().
 */
function gesso_helper_form_system_theme_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // Work-around for a core bug affecting admin themes.
  // See https://www.drupal.org/docs/8/theming-drupal-8/creating-advanced-theme-settings.
  if (isset($form_id)) {
    return;
  }

  if ($form['config_key'] && $form['config_key']['#value']) {
    $theme = explode('.', $form['config_key']['#value'])[0];
  } else {
    $theme = \Drupal::theme()->getActiveTheme()->getName();
  }

  $form['buttons'] = [
    '#type' => 'details',
    '#title' => t('Buttons'),
    '#open' => TRUE,
  ];
  $form['buttons']['button_sizes'] = [
    '#type' => 'textarea',
    '#title' => t('Button Sizes'),
    '#default_value' => theme_get_setting('button_sizes', $theme) ?? "button|Standard\nbutton.button--small|Small\nbutton.button--large|Large",
    '#description' => t('Enter one or more classes on each line in the format: classA.classB|Label. Example: button.button--small|Small'),
    '#required' => TRUE,
  ];
  $form['buttons']['button_styles'] = [
    '#type' => 'textarea',
    '#title' => t('Button Styles'),
    '#default_value' => theme_get_setting('button_styles', $theme) ?? "button|Primary\nbutton.button--secondary|Secondary\nbutton.button--danger|Danger",
    '#description' => t('Enter one or more classes on each line in the format: classA.classB|Label. Example: button.button--danger|Danger'),
    '#required' => TRUE,
  ];
}
