# This is a basic workflow to help you get started with Actions

name: Publish demo site

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the 4.x branch
  push:
    branches: [ 5.x ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm ci
      # Runs a single command using the runners shell
      - name: Deploy Storybook to Github Pages
        run: npm run deploy-storybook -- --ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
